services:
  yonken0405-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # 小文字で統一、インデントを正しく
    container_name: yonken0405-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on:
      - db

  db:  # データベースの設定
    image: postgres:latest  # PostgreSQLの最新イメージを使用
    container_name: yonken0405-db  # コンテナ名
    environment:
      - POSTGRES_USER=user  # データベースのユーザー名
      - POSTGRES_PASSWORD=password  # データベースのパスワード
      - POSTGRES_DB=yonken0405-db  # データベース名
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # PostgreSQLのポートを公開

  pgadmin:
    image: dpage/pgadmin4
    container_name: yonken0405-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: yonken0405@admin.com  # 管理者用のメールアドレス
      PGADMIN_DEFAULT_PASSWORD: yonken0405  # 管理者用のパスワード
    ports:
      - "8080:80"  # pgAdminのポート
    depends_on:
      - db  # dbコンテナが起動してからpgAdminを起動


  yonken0405-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # 小文字で統一、インデントを正しく
    container_name: yonken0405-frontend
    tty : true
    ports:
    #ローカルのポートをコンテナのポートにマッピング
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_SERVER_HOST=0.0.0.0
    restart: always
    depends_on:
      - yonken0405-backend

networks:
  app-network:  # ネットワークを定義
    driver: bridge
